require 'middleman-gh-pages'
require 'rouge'

namespace :syntax do
  theme_css_path = 'source/stylesheets/syntax-highlight.css'
  desc "Write rouge theme css to #{theme_css_path}"
  task :theme, :theme do |t, args|
    theme = args[:theme] || 'thankful_eyes'
    puts "Writing theme '#{theme}' to #{theme_css_path}"
    File.open(theme_css_path, 'w') { |f|
      f.puts "/* generated by rake syntax:theme[#{theme}] */"
      f.write Rouge::Theme.find(theme).render(scope: '.highlight')
    }
  end

  desc 'List all rouge themes'
  task :themes do
    puts Rouge::Theme.registry.keys * "\n"
  end
end